def create_execution(exec_id, workflow, input): ...


def get_execution(exec_id): ...


def write_history(exec_id, i, result): ...


def advance(exec_id, i, ver, result, wake=None, sleeping=False): ...


def complete(exec_id): ...


def due_executions(now): ...
